workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        XCODE_PROJECT: "Runner.xcodeproj"
        XCODE_SCHEME: "Runner"
        EXPORT_OPTIONS_PLIST: "ExportOptions.plist"
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Build iOS app and export IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=$EXPORT_OPTIONS_PLIST

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - build/ios/ipa/*.log
