workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - appstore
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Decode signing assets
        script: |
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          echo $CM_PROVISIONING_PROFILE | base64 --decode > /tmp/profile.mobileprovision

      - name: Set up code signing
        script: |
          keychain initialize
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
          xcode-project use-profiles --profile /tmp/profile.mobileprovision

      - name: Build IPA
        script: |
          flutter build ipa --release

      - name: Upload to TestFlight
        script: |
          app-store-connect publish \
            --issuer-id=$APP_STORE_CONNECT_ISSUER_ID \
            --key-id=$APP_STORE_CONNECT_KEY_IDENTIFIER \
            --private-key=$APP_STORE_CONNECT_PRIVATE_KEY \
            --app-id=6745463805

    artifacts:
      - build/ios/ipa/*.ipa
