workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS without code signing
        script: |
          flutter build ios --release --no-codesign
      - name: Create IPA using xcodebuild and ExportOptions.plist
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath build/ios/archive.xcarchive \
                     archive

          xcodebuild -exportArchive \
                     -archivePath build/ios/archive.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
