workflows:
  ios-release:
    name: iOS Release Build (Auto Signing)
    environment:
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.irishpuffin.bellymeter"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
      - name: Build and export IPA with automatic code signing
        script: |
          flutter build ios --release --no-codesign
          xcodebuild archive \
            -workspace ios/$XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -archivePath build/ios/archive.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates

          xcodebuild -exportArchive \
            -archivePath build/ios/archive.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/ios/ipa \
            -allowProvisioningUpdates
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
