workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
    code_signing:
      certificate_id: JAweXBk3
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: J98GD4D42Q
          issuer_id: a377f6f0-f5d3-4367-9a84-0c7ae99fa81e
        submit_to_testflight: true
