 workflows:   
    ios-workflow:
      name: iOS Workflow
      max_build_duration: 120
      instance_type: mac_mini_m2
      integrations:
        app_store_connect: Codemagic Key
      environment:
        xcode: 16.2
        flutter: stable
        ios_signing:
         distribution_type: app_store
         certificate: belly_ios_distribution_cert
         provisioning_profile: belly_ios_app_store_profile
         bundle_identifier: .com.irishpuffin.bellymeter


        vars:
          APP_ID: 6745463805
      scripts:
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles
        - name: Get Flutter packages
          script: |
            flutter packages pub get
        - name: Install pods
          script: |
            find . -name "Podfile" -execdir pod install \;
        - name: versioning
          script: |
            LATEST_BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1))
            cd ./ios
            agvtool new-version -all $(($LATEST_BUILD_NUMBER))
            agvtool new-marketing-version 1.0.$(($LATEST_BUILD_NUMBER))
        - name: Flutter build ipa and automatic versioning
          script: |
            flutter build ipa --release \
              --export-options-plist=/Users/builder/export_options.plist
      artifacts:
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        - /Users/builder/clone/build/ios/ipa/*.ipa
      publishing:
        email:
          recipients:
            - alex.niemer@gmail.com
          notify:
            success: true 
            failure: false
        app_store_connect:
          auth: integration