workflows:
  ios-release:
    name: iOS Release Build
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_ID: "com.irishpuffin.bellymeter"
        EXPORT_OPTIONS_PLIST: "ExportOptions.plist"
        DEVELOPMENT_TEAM: "JAweXBk3"
        PROVISIONING_PROFILE_SPECIFIER: "a420072c-273c-40c7-8b23-c51c5bcc3910"
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install

      - name: Set code signing settings in project
        script: |
          xcode-project use-profiles \
            --project ios/Runner.xcodeproj \
            --bundle-id $APP_ID \
            --profile "$PROVISIONING_PROFILE_SPECIFIER"

      - name: Build iOS without code signing
        script: |
          flutter build ios --release --no-codesign

      - name: Archive and Export IPA with manual signing
        script: |
          mkdir -p build/ios/ipa

          xcodebuild archive \
            -workspace ios/$XCODE_WORKSPACE \
            -scheme $XCODE_SCHEME \
            -configuration Release \
            -archivePath build/ios/archive.xcarchive \
            -destination 'generic/platform=iOS' \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
            PRODUCT_BUNDLE_IDENTIFIER=$APP_ID

          xcodebuild -exportArchive \
            -archivePath build/ios/archive.xcarchive \
            -exportOptionsPlist $EXPORT_OPTIONS_PLIST \
            -exportPath build/ios/ipa

          echo "Contents of build/ios/ipa:"
          ls -lah build/ios/ipa

          if [ ! -f build/ios/ipa/*.ipa ]; then
            echo "❌ IPA file was not created!"
            exit 1
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - build/ios/ipa/*.log
