workflows:
  ios-release:
    name: iOS Release Build
    environment:
      vars:
        APP_ID: "com.irishpuffin.bellymeter"
        DEVELOPMENT_TEAM: "JAweXBk3"
        PROVISIONING_PROFILE_NAME: "Belly Code Signing"
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install

      - name: Build and export .ipa with manual signing
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-flags "-allowProvisioningUpdates" \
            --export-options-plist ExportOptions.plist \
            --provisioning-profile "$PROVISIONING_PROFILE_NAME" \
            --team-id "$DEVELOPMENT_TEAM" \
            --bundle-id "$APP_ID"

          echo "IPA directory contents:"
          ls -lah build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
      - build/ios/ipa/*.log
